contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
canonifyurls = true
baseurl = "/"
theme = "hugo-tufte"
title = "The Madrone Library"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = ""
  copyrightHolder = "Nick Klagge"
  showPoweredBy = true

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-book-open fa-lg'></i> "
  weight = -110 
  identifier = "about"
  url = "/about"
[[menu.nav]]
  name = "All Posts"
  pre = "<i class='fab fa-pagelines fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fas fa-crow fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
#[[menu.footer]]
#  name = ""
#  pre = "<i class='fa fa-github fa-2x'></i> "
#  weight = -100 
#  identifier = "github"
#  url = "https://github.com/shawnohare/hugo-tufte"
#[[menu.footer]]
#  name = ""
#  pre = "<i class='fa fa-twitter fa-2x'></i> "
#  weight = -90 
#  identifier = "twitter"
#  url = "https://twitter.com"
